# Generated by Django 2.2.4 on 2020-12-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20201215_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='productCategory', to='ventas.Category'),
        ),
    ]
